### ISSUE TITLE
数据库表关系

### ISSUE THREAD

**Issue by leikui** [lijile/easyflow#1]
能发下各表之间的关系吗

**Comment by lijile** [comment]
亲 ，我已经收到您的邮件，若有急事请致电：13751720747

**Comment by lijile** [comment]
抱歉，前一段时间比较忙没有看到。
![ER关系图](https://user-images.githubusercontent.com/13581251/150138206-59b7b41b-e5e9-46ed-ab04-364ab9bb9d96.jpg)
